<?php

$conn = mysqli_connect("localhost","root", "jameskinuthia", "alexa");
if (!$conn) {
	# code...
	die("Connection Failed:".mysqli_connect_error());

}
date_default_timezone_set('Africa/Nairobi');
$speed=rand ( 1 , 15 );
$km=$speed."KM/H";
//echo $km;
$longitude="39.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
// echo "  ";
// echo $longitude;
// echo "  ";
// echo $latitude;
$date=date('d-m-Y');
$time=date('H:i:s');
$select="SELECT * from work where serial='16100001994'";



$query=mysqli_query($conn,$select);
$i=1;
$row=mysqli_fetch_array($query);
	# code...
	
	$serial='0'.$row['serial'];
	echo nl2br($serial."  \n");
	$sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);


sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
sleep(5);
$time=date('H:i:s');
$speed=rand ( 1 , 15 );
$km= $speed."KM/H";
//echo $km;
$longitude="36.".rand ( 100000 , 999999 )."E";
$latitude="1.".rand ( 100000 , 999999 )."S";
echo nl2br($serial."  \n");
        $sql="INSERT INTO `data1`( `vehicle`, `date`, `time`, `longitude`, `latitude`, `velocity`, `poweralarm`, `speedDisConn`)VALUES ('$serial','$date','$time','$longitude','$latitude','$km','0','0')";
mysqli_query($conn,$sql);
?>
